apiVersion: v1
data:
  OAUTH2_PROXY_CLIENT_ID: NDA3NDMxNTU2MDg1LWpjNDFlMmkwY2twaXJkZ2Q3NW9mcDZyZGVlaTV1b2hzLmFwcHMuZ29vZ2xldXNlcmNvbnRlbnQuY29t
  OAUTH2_PROXY_CLIENT_SECRET: Y3VVYXRCMEdoMTZYd1l3Ri1HSTJQSWR1
  OAUTH2_PROXY_COOKIE_SECRET: Yld5RTJPd1k5QVpfaUQ1ajF2a2dzblE9PQ==
kind: Secret
metadata:
  creationTimestamp: 2018-06-27T12:35:18Z
  name: oauth
  namespace: aleposca
  resourceVersion: "5673968"
  selfLink: /api/v1/namespaces/aleposca/secrets/oauth
  uid: 8cd1c0f6-7a06-11e8-8e93-fa163ea11bcd
type: Opaque
