apiVersion: v1
data:
  OAUTH2_PROXY_CLIENT_ID: NDA3NDMxNTU2MDg1LWpjNDFlMmkwY2twaXJkZ2Q3NW9mcDZyZGVlaTV1b2hzLmFwcHMuZ29vZ2xldXNlcmNvbnRlbnQuY29t
  OAUTH2_PROXY_CLIENT_SECRET: Y3VVYXRCMEdoMTZYd1l3Ri1HSTJQSWR1
  OAUTH2_PROXY_COOKIE_SECRET: Yld5RTJPd1k5QVpfaUQ1ajF2a2dzblE9PQ==
kind: Secret
metadata:
  creationTimestamp: 2018-06-27T12:35:18Z
  name: oauth
  namespace: aleposca
  resourceVersion: "5673968"
  selfLink: /api/v1/namespaces/aleposca/secrets/oauth
  uid: 8cd1c0f6-7a06-11e8-8e93-fa163ea11bcd
type: Opaque
---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  labels:
    k8s-app: oauth
  name: oauth
  namespace: aleposca
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      k8s-app: oauth
  template:
    metadata:
      labels:
        k8s-app: oauth
    spec:
      containers:
      - name: oauth
        image: bcawthra/oauth2_proxy:latest
        args:
        - --email-domain=gmail.com
        - --upstream=file:///dev/null
        - --http-address=0.0.0.0:4180
        env:
        - name: OAUTH2_PROXY_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: oauth
              key: OAUTH2_PROXY_CLIENT_ID
        - name: OAUTH2_PROXY_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: oauth
              key: OAUTH2_PROXY_CLIENT_SECRET
        - name: OAUTH2_PROXY_COOKIE_SECRET
          valueFrom:
            secretKeyRef:
              name: oauth
              key: OAUTH2_PROXY_COOKIE_SECRET
        - name: OAUTH2_PROXY_PROVIDER
          value: "google"
        ports:
        - containerPort: 4180
          protocol: TCP
---
kind: Service
apiVersion: v1
metadata:
  labels:
    k8s-app: oauth 
  name: oauth
  namespace: aleposca
spec:
  ports:
  - name: oauth
    port: 4180
    targetPort: 4180
  selector:
    k8s-app: oauth
